### ISSUE TITLE
Remove uneeded dependencies and/or load dependencies

### ISSUE THREAD

**Issue by J-Moravec** [alejandrohagan/1br#2]
Primarily issue of `generate_data.R`, but also occurs in other places.

I like being explicit (`package::function`). However, one needs to ensure the packages do exist (they are automatically loaded with `::` if they exist). I would prefer to get the error about the missing package at the start.

Particularly in the `generate_data.R`, `tibble` is never used, instead, data are directly saved using `data.table`. So either use `data.table` or `data.frame`. `cli` can be also removed, `prettyunits` package can be replaced by a custom function (probably one-liner). Base package should not have to be called using `::` unless you are expecting conflict.

**Comment by usrbinr** [comment]
Thank you! I believe the latest commit closed this out
