### ISSUE TITLE
Run individual benchmark in clean R session

### ISSUE THREAD

**Issue by J-Moravec** [alejandrohagan/1br#4]
The `1brow.R` runs each benchmark using `source()`. This means that every benchmark is run in the same session, with potential side-effects.

https://github.com/alejandrohagan/1br/blob/a9929426206e8bd4f38505cb28bb9881a97f36bb/1brow.R#L11-L18

It would be cleaner if each benchmark was run in a clean session instead. Either using `system2` or the R package `callr`. This way, every individual benchmark will be run in insolation independently on whatever happened in the main running script.

**Comment by usrbinr** [comment]
hi! thanks for this one. I'm not as familiar with how to use system2 or callr  yet so I'll put this as an enhancement

**Comment by usrbinr** [comment]
hi -- I updated the code and source each script in system2() to helpfully run each in a clean environment. 

Thank you again for all your comments! it helped me become a better programmer

**Comment by J-Moravec** [comment]
I can keep them coming if you want:)

**Comment by usrbinr** [comment]
sure ! happy to hear them. For some reason the data.table performance drops after the dataset grows beyond 500M rows -- but this isn't being replicated by others. 

Even with the system2() call -- it appears something else is going on.
