### ISSUE TITLE
Sharing Reprex for {tidytable}, {tidyverse}, and {tidypolars}

### ISSUE THREAD

**Issue by frankiethull** [alejandrohagan/1br#6]
1br
fth
2024-01-05
# load libs -----
library(polars)
library(tidypolars)
########   print.RPolarsDataFrame polars
library(dplyr)
######## 
######## 
######## 
########     intersect, setdiff, setequal, union
rows <- c(1000,       #1thou
          10000,      #10 thou
          100000,     #100thou
          10000000,   #10 mill
          1000000000) #1bill
### BENCH::MARK ################################
many_marks <- function(rows){

  #### r dataframe
df <- data.frame(
  x = rnorm(n = rows)
)
  #### polars dataframe
rs <- df |> tidypolars::as_polars()

bench <- bench::mark(
   tidytable = df |>
    tidytable::summarize(
      min  = min(x),
      mean = mean(x),
      max  = max(x)
    )  |> as.data.frame(),
   tidyverse = df |>
    dplyr::summarize(
      min  = min(x),
      mean = mean(x),
      max  = max(x)
    ),
   tidypolars = df |> 
    tidypolars::as_polars() |> # type conversions slows down the process
    dplyr::summarize(
      min  = min(x),
      mean = mean(x),
      max  = max(x)
    ) |> tidypolars::to_r(),
   tidypol_rs = rs |>       # the speed benefit is only if upstream processes already are polars objects 
     dplyr::summarize(
       min  = min(x),
       mean = mean(x),
       max  = max(x)
     ) |> tidypolars::to_r(),
   iterations = 10
)

return(bench)

}
## results ################

benches <- lapply(rows, many_marks)

all_results <-
do.call(rbind, benches) |>
  mutate(
    row_amount = rep(rows, each = 4)
  )

all_results |>
  select(expression, row_amount, median) |>
  mutate(
    row_amount = scales::number(row_amount, big.mark = ",")
  )
######## 20 tidypol_rs 1,000,000,000 841.88ms
# library(bench)
# autoplot(all_results)
sessionInfo()
#### 
#### 
#### 
#### 
#### 
#### 
####

**Comment by etiennebacher** [comment]
Hi, I'm the author of `tidypolars` and contributor to `polars`. I just want to point out that it is expected that `polars` (and therefore `tidypolars`) is slower when you do the conversion `R data.frame -> polars DataFrame -> R data.frame` in the benchmark. 

When you have large data and want to use `polars`/`tidypolars`, the expected workflow is to use `polars` to read or scan the data directly in the "`polars` format" using `pl$read_*()` or `pl$scan_*()` functions. You should not use `as_polars()` on large datasets that were read by other packages, `as_polars()` is only here to convert small/medium size datasets to make it easier to demonstrate the `tidypolars` workflow.

Therefore, in the benchmark results above, I would rely more on the `tidypol_rs` row, not the `tidypolars` one.

**Comment by frankiethull** [comment]
@etiennebacher  - thank you for this package, it makes polars way easier to work with. The initial syntax had me gasp, when I cam across this R pkg it was a lifesaver.  And I plan on using tidypolars instead of tidytable on larger datasets. 

I had a comment up above ('speed benefit is only if upstream processes already are polars objects'). I was doing this benchmarks initial to argue for upsteam polars processing at my company, before I shared here. That's why I have both benchmarks in there, thanks for elaborating on the results. That was my takeaway as well

@alejandrohagan - hope this code was helpful, I mentioned I'd throw a reprex on here for you, just now back on this ticket and the format came out ugly. Apologies!
